import type { NextPage } from 'next'
import Head from 'next/head'
import Account from '../components/Account'
import NewAccount from '../components/NewAccount'
import NavBar from '../components/NavBar'
import { useState, useContext } from 'react'
import AccountModal from '../components/AccountModal'
import { AccountContext } from "../lib/AccountsContext"

const Accounts: NextPage = () => {

    const [isOpen, setIsOpen  ] = useState(false)
    const accountContext = useContext(AccountContext)
    
    return (
        <>
        <Head>
            <title>Accounts</title>
            <meta name="Accounts" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <AccountModal isOpen={isOpen} currentUser={"hugh"} setIsOpen={setIsOpen} />
        <div className='flex gap-10 w-full justify-center items-center login'>
            <Account name="user" />
            { accountContext.accounts.map((account, index) => {
                return <Account key={index} name={account.username} />
            })
            }
            <NewAccount isOpen={isOpen} setIsOpen={setIsOpen} />
        </div>
        </>
    )
}

export default Accounts