import type { NextPage } from 'next'
import Head from 'next/head'
import Account from '../components/Account'
import NewAccount from '../components/NewAccount'

const Accounts: NextPage = () => {
    return (
        <div>
        <Head>
            <title>Accounts</title>
            <meta name="Accounts" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className='text-white'>Accounts</h1>
        <div className='flex gap-10 w-full justify-center items-center'>
            <Account name="user" />
            <NewAccount />
        </div>
        </div>
    )
}

export default Accounts