import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
// import { useEffect, useState } from "react";
import NavBar from "../components/NavBar";
// import FeaturedMovie from "../models/FeaturedMovie";
import Feature from "../components/Feature";
import FeatureInfo from "../components/FeatureInfo";
import MovieRow from "../components/MovieRow";
const Home: NextPage = () => {
  

  return (
    <div className="bg-zinc-900 mb-10 home">
      <Head>
        <title>Notflix</title>
        <meta name="Fake Netflix" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
        <div className="">
          <FeatureInfo />
        {/* <div className=" z-50 absolute text-white top-28 left-10 info">
            <h1 className="text-4xl font bold">test</h1>
          </div> */}
          <Feature />
        </div>
        <div className="mb-20 mt-10">
        <MovieRow />       
        </div>
        <div className="mb-20 mt-10">
        <MovieRow />       
        </div>
        <div className="mb-20 mt-10">
        <MovieRow />       
        </div>
        {/* <div className="h-96"></div> */}
    </div>
  );
};

export default Home;
