import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import MovieCard from "../components/MovieCard";
import MovieRow from "../components/MovieRow";
import { LibraryContext } from '../lib/FavoritesContext';
import { useContext } from "react";
import { AccountContext } from "../lib/AccountsContext";

const MyLibrary: NextPage = () => {
    const movies = useContext(LibraryContext)
    const accountContext = useContext(AccountContext)
    
    return (
      <div className="library overflow-hidden over">
        <Head>
            <title>My Library</title>
            <meta name="My Library" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <div className="p-5">
            {/* <h1 className="text-zinc-200 mt-20 text-3xl w-full flex justify-center">My Library</h1> */}
        </div>

      {
        !accountContext.currentAccount?.library  ? (<h1 className="text-zinc-200 mt-20 text-3xl w-full flex justify-center">No movies in your library</h1>) : ( 
      <>
      <MovieRow movies={movies.library} query="" />
      <MovieRow movies={movies.library} query="" />
      </>
    )}
      </div>
    );
};

export default MyLibrary;