import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import MovieCard from "../components/MovieCard";
import MovieRow from "../components/MovieRow";
import { LibraryContext } from '../lib/FavoritesContext';
import { useContext } from "react";

const MyLibrary: NextPage = () => {
    const movies = useContext(LibraryContext)
    return (
      <div className="library">
        <Head>
            <title>My Library</title>
            <meta name="My Library" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <div className="p-5">
            <h1 className="text-zinc-200 mt-20 text-3xl w-full flex justify-center">My Library</h1>
        </div>

      <MovieRow movies={movies.library} />
      <MovieRow movies={movies.library} />

      </div>
    );
};

export default MyLibrary;