import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import MovieRow from "../components/MovieRow";
import { useContext, useEffect, useState } from "react";
import { AccountContext } from "../lib/AccountsContext";
import { collection, getDocs } from "firebase/firestore";
import { auth, db } from "../lib/firebase";
import { useAuthState } from "react-firebase-hooks/auth";

const MyLibrary: NextPage = () => {
  const [movies, setMovies] = useState<any>([]);
  const accountContext = useContext(AccountContext);
  const [user] = useAuthState(auth);

  useEffect(() => {
    if (user) getLibrary();
  }, [user]);

  //get library from firestore of the current account
  const getLibrary = async () => {
    const querySnapshot = await getDocs(
      collection(
        db,
        "users",
        user!.uid,
        "accounts",
        accountContext.currentAccount,
        "library"
      )
    );
    querySnapshot.forEach((doc) => {
      setMovies((movies: any) => [...movies, doc.data()]);
    });
  };

  return (
    <div className="library overflow-hidden over">
      <Head>
        <title>My Library</title>
        <meta name="My Library" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="p-5"></div>

      {movies.length < 1 ? (
        <h1 className="text-zinc-200 mt-20 text-3xl w-full flex justify-center">
          No movies in your library
        </h1>
      ) : (
        <>
          <MovieRow movies={movies} query="" />
          <MovieRow movies={movies} query="" />
        </>
      )}
    </div>
  );
};

export default MyLibrary;
